# Generated by Django 6.0.3 on 2026-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_prestamo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca_modelo',
            field=models.CharField(blank=True, help_text='Marca, modelo o numeración (Ej: MOLTEN F523 #5)', max_length=150, null=True),
        ),
    ]
