# Generated by Django 6.0.3 on 2026-10-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Motivo por el cual la solicitud fue rechazada', null=True),
        ),
    ]
