# Generated by Django 6.0.3 on 2026-10-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_prestamo_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado_devolucion',
            field=models.CharField(blank=True, choices=[('BUENO', 'Buen Estado'), ('DESGASTE', 'Desgaste Normal'), ('DANADO', 'Dañado / Averiado')], default='BUENO', help_text='Estado físico de los equipos al ser devueltos', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='foto_devolucion',
            field=models.ImageField(blank=True, help_text='Fotografía de evidencia del estado del equipo devuelto', null=True, upload_to='devoluciones/'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='observaciones_devolucion',
            field=models.TextField(blank=True, help_text='Observaciones o reporte de averías/daños al momento de la devolución', null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió el recordatorio preventivo de devolución'),
        ),
    ]
