import { Equipment, LoanRequest, Sanction } from './types';

export const MOCK_EQUIPMENT: Equipment[] = [
  {
    id: '1',
    name: 'Pelota de Baloncesto',
    category: 'Bolas',
    description: 'Balón oficial para cancha de baloncesto',
    available: 15,
    total: 20,
    imageUrl: '/pelotabasket.jpg',
    condition: 'excellent',
  },
  {
    id: '2',
    name: 'Pelota de Fútbol',
    category: 'Bolas',
    description: 'Balón para fútbol de campo',
    available: 10,
    total: 15,
    imageUrl: '/pelotafutbolcamp.png',
    condition: 'good',
  },
  {
    id: '3',
    name: 'Pelota de Béisbol',
    category: 'Bolas',
    description: 'Pelota oficial para béisbol',
    available: 8,
    total: 12,
    imageUrl: '/pelotabeisbol.png',
    condition: 'good',
  },
  {
    id: '4',
    name: 'Conos Grandes',
    category: 'Accesorios',
    description: 'Conos para delimitar áreas y ejercicios de agilidad',
    available: 12,
    total: 15,
    imageUrl: '/conosgrandes.png',
    condition: 'good',
  },
  {
    id: '5',
    name: 'Conos Pequeños',
    category: 'Accesorios',
    description: 'Conos pequeños para entrenamiento de velocidad',
    available: 20,
    total: 25,
    imageUrl: '/conospeq.png',
    condition: 'excellent',
  },
  {
    id: '6',
    name: 'Guantes de Fútbol',
    category: 'Accesorios',
    description: 'Guantes de portero para entrenamiento',
    available: 5,
    total: 10,
    imageUrl: '/guantesfut.png',
    condition: 'excellent',
  },
];

export const MOCK_LOAN_REQUESTS: LoanRequest[] = [
  {
    id: '1',
    studentId: '2',
    studentName: 'Juan García',
    equipmentId: '1',
    equipmentName: 'Basketball',
    quantity: 2,
    requestDate: new Date('2026-03-10'),
    dueDate: new Date('2026-03-15'),
    status: 'approved',
    notes: 'For intramural tournament',
  },
  {
    id: '2',
    studentId: '3',
    studentName: 'María López',
    equipmentId: '5',
    equipmentName: 'Yoga Mat',
    quantity: 1,
    requestDate: new Date('2026-03-12'),
    dueDate: new Date('2026-03-20'),
    status: 'pending',
  },
];

export const MOCK_SANCTIONS: Sanction[] = [
  {
    id: '1',
    studentId: '4',
    studentName: 'Carlos Rodríguez',
    reason: 'Equipment returned damaged',
    date: new Date('2026-02-20'),
    severity: 'warning',
    expiryDate: new Date('2026-05-20'),
  },
];
